# Generated by Django 4.2.6 on 2023-11-18 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0002_entregable_profesor_articles_creador_estudiante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='creador',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='creador',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
