# Generated by Django 4.2.6 on 2023-11-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0003_remove_article_creador_remove_curso_creador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(max_length=300, null=True, upload_to='blogImages'),
        ),
    ]
