# Generated by Django 4.2.6 on 2023-11-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0007_alter_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='blogImages'),
        ),
    ]
